# My default dev box
FROM v4tech/base:latest
MAINTAINER Stewart V. Wright <stewart@vifortech.com>

RUN apt-get install -y --no-install-recommends \
        autoconf \
        emacs \
        gcc

# Default port for ipython notebook
EXPOSE 8888
