# My default dev box
FROM v4tech/base:latest
MAINTAINER Stewart V. Wright <stewart@vifortech.com>

RUN apt-get install -y \
        autoconf \
        emacs \
        gcc \
        make \
        libc6-dev

# Default port for ipython notebook
EXPOSE 8888
